=== jparc-k18/k18-analyzer/param/schema/channel_map.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema
    attributeFormDefault="unqualified"
    elementFormDefault="unqualified"
    xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="channel_map" type="channel_mapType"/>


  <!-- ______________________________________________________________________-->
  <!-- ______________________________________________________________________-->
  <!-- _________________________________________________________________________
       attributeGroup definition
  -->
  <!-- _________________________________________________________________________
       <unpackerAttrs>
  -->
  <xs:attributeGroup name="unpackerAttrs">
    <xs:attribute name="decode" type="xs:string" default="y"/>
    <xs:attribute name="dump"   type="xs:string" default="n"/>
    <xs:attribute name="unpack" type="xs:string" default="y"/>
  </xs:attributeGroup>

  <!-- _________________________________________________________________________
       <finesseAttrs>
  -->
  <xs:attributeGroup name="finesseAttrs">
    <xs:attribute name="slot" type="xs:string" use="required"/>
    <xs:attributeGroup ref="unpackerAttrs"/>
  </xs:attributeGroup>

  <!-- _________________________________________________________________________
       <tkoAttrs>
  -->
  <xs:attributeGroup name="tkoAttrs">
    <xs:attribute name="ma" type="xs:string" use="required"/>
    <xs:attributeGroup ref="unpackerAttrs"/>
  </xs:attributeGroup>

  <!-- _________________________________________________________________________
       <feraAttrs>
  -->
  <xs:attributeGroup name="feraAttrs">
    <xs:attribute name="ma" type="xs:string" use="required"/>
    <xs:attributeGroup ref="unpackerAttrs"/>
  </xs:attributeGroup>

  <!-- _________________________________________________________________________
       <vmeAttrs>
  -->
  <xs:attributeGroup name="vmeAttrs">
    <xs:attribute name="address" type="xs:string" use="required"/>
    <xs:attributeGroup ref="unpackerAttrs"/>
  </xs:attributeGroup>

  <!-- _________________________________________________________________________
       <nodeAttrs>
  -->
  <xs:attributeGroup name="nodeAttrs">
    <xs:attribute name="node_id" type="xs:string" use="required"/>
    <xs:attribute name="name"    type="xs:string" use="required"/>
    <xs:attributeGroup ref="unpackerAttrs"/>
  </xs:attributeGroup>



  <!-- ______________________________________________________________________-->
  <!-- ______________________________________________________________________-->
  <!-- _________________________________________________________________________
       group definition
  -->
  <!-- _________________________________________________________________________
       <feGroup>
  -->
  <xs:group name="feGroup">
    <xs:choice>
      <xs:element name="FE"  type="FEType"/>
      <xs:element name="for" type="fe_forType"/>
    </xs:choice>
  </xs:group>

  <!-- _________________________________________________________________________
       <finesseGroup>
  -->
  <xs:group name="finesseGroup">
    <xs:choice>
      <xs:element name="FinesseEncoderPPG" type="FinesseType"/>
      <xs:element name="FinesseEncoder"    type="FinesseType"/>
      <xs:element name="FinessePtdc"       type="FinesseType"/>
      <xs:group   ref="feGroup"/>
    </xs:choice>
  </xs:group>

  <!-- _________________________________________________________________________
       <tkoGroup>
  -->
  <xs:group name="tkoGroup">
    <xs:choice>
      <xs:element name="Tko"      type="TkoType"/>
      <xs:element name="TkoDrT"   type="TkoType"/>
      <xs:element name="TkoDrTII" type="TkoType"/>
      <xs:element name="TkoRm"    type="TkoRmType"/>
      <xs:element name="TkoMHTdc" type="TkoMHTdcType"/>
      <xs:element name="TkoMHTdcCSds" type="TkoMHTdcCSdsType"/>
      <xs:group   ref="feGroup"/>
    </xs:choice>
  </xs:group>

  <!-- _________________________________________________________________________
       <feraGroup>
  -->
  <xs:group name="feraGroup">
    <xs:choice>
      <xs:element name="FeraAD413A"   type="FeraType"/>
      <xs:element name="Fera3377"     type="FeraType"/>
      <xs:group   ref="feGroup"/>
    </xs:choice>
  </xs:group>

  <!-- _________________________________________________________________________
       <vmeModuleGroup>
  -->
  <xs:group name="vmeModuleGroup">
    <xs:choice>
      <xs:element name="VmeAPVDaq"     type="VmeModuleType"/>
      <xs:element name="VmeSmp"        type="VmeSmpType"/>
      <xs:element name="VmeRpv130"     type="VmeModuleType"/>
      <xs:element name="VmeRpv100"     type="VmeModuleType"/>
      <xs:element name="VmeCaenV775"   type="VmeModuleType"/>
      <xs:element name="VmeCaenV792"   type="VmeModuleType"/>
      <xs:element name="VmeCaenV820"   type="VmeModuleType"/>
      <xs:element name="VmeCaenV830"   type="VmeModuleType"/>
      <xs:element name="VmeCaenV1724"  type="VmeModuleType"/>
      <xs:element name="VmeEmc"        type="VmeModuleType"/>
      <xs:element name="VmeInputReg"   type="VmeModuleType"/>
      <xs:element name="VmeTdc64M"     type="VmeModuleType"/>
      <xs:element name="VmeRm"         type="VmeModuleType"/>
      <xs:element name="VmeAmt"        type="VmeModuleType"/>
      <xs:element name="VmeUmem"       type="VmeUmemType"/>
      <xs:element name="HBJTimeStamp"  type="VmeModuleType"/>
      <xs:element name="VVmeCamacRm"   type="VmeModuleType"/>
      <xs:element name="VVmeFERA4300B" type="VmeModuleType"/>
      <xs:element name="VVmeCoinReg"   type="VmeModuleType"/>
      <xs:element name="VmeV1290A"     type="VmeModuleType"/>
      <xs:group   ref="feGroup"/>
    </xs:choice>
  </xs:group>

  <!-- _________________________________________________________________________
       <nodeGroup>
  -->
  <xs:group name="nodeGroup">
    <xs:choice>
      <xs:element name="SoyTimeStamp"    type="DAQNodeType"/>
      <xs:element name="Hul3DMtx"        type="DAQNodeType"/>
      <xs:element name="HulScaler"       type="DAQNodeType"/>
      <xs:element name="HulMHTdc"        type="DAQNodeType"/>
      <xs:element name="HulHRTdc"        type="DAQNodeType"/>
      <xs:element name="HulMsT"          type="DAQNodeType"/>
      <xs:element name="HulMassTrigFera" type="DAQNodeType"/>
      <xs:element name="HulResetTime"    type="DAQNodeType"/>
      <xs:element name="HulUmem"         type="DAQNodeType"/>
      <xs:element name="VmeMaster"       type="VmeMasterType"/>
      <xs:element name="Copper"          type="CopperType"/>
      <xs:element name="CopperLite"      type="CopperType"/>
      <xs:element name="Easiroc"         type="DAQNodeType"/>
      <xs:element name="VmeEasiroc"      type="DAQNodeType"/>
      <xs:element name="DAQNode"         type="DAQNodeType"/>
      <xs:group   ref="feGroup"/>
    </xs:choice>
  </xs:group>

  <!-- _________________________________________________________________________
       <unpackerGroup>
  -->
  <xs:group name="unpackerLoopGroup">
    <xs:choice>
      <xs:element name="DAQNode"            type="DAQNodeType"/>
      <xs:element name="Copper"             type="CopperType"/>
      <xs:element name="CopperLite"         type="CopperType"/>
      <xs:element name="Easiroc"            type="DAQNodeType"/>
      <xs:element name="VmeEasiroc"         type="DAQNodeType"/>
      <xs:element name="VmeMaster"          type="VmeMasterType"/>
      <xs:element name="SoyTimeStamp"       type="DAQNodeType"/>
      <xs:element name="Hul3DMtx"           type="DAQNodeType"/>
      <xs:element name="HulScaler"          type="DAQNodeType"/>
      <xs:element name="HulMHTdc"           type="DAQNodeType"/>
      <xs:element name="HulHRTdc"           type="DAQNodeType"/>
      <xs:element name="HulMsT"             type="DAQNodeType"/>
      <xs:element name="HulMassTrigFera"    type="DAQNodeType"/>
      <xs:element name="HulUmem"            type="DAQNodeType"/>
      <xs:element name="HulResetTime"       type="DAQNodeType"/>

      <xs:element name="VmeRpv100"          type="VmeModuleType"/>
      <xs:element name="VmeRpv130"          type="VmeModuleType"/>
      <xs:element name="VmeCaenV775"        type="VmeModuleType"/>
      <xs:element name="VmeCaenV792"        type="VmeModuleType"/>
      <xs:element name="VmeCaenV820"        type="VmeModuleType"/>
      <xs:element name="VmeCaenV830"        type="VmeModuleType"/>
      <xs:element name="VmeCaenV1724"       type="VmeModuleType"/>
      <xs:element name="VmeEmc"             type="VmeModuleType"/>
      <xs:element name="VmeInputReg"        type="VmeModuleType"/>
      <xs:element name="VmeTdc64M"          type="VmeModuleType"/>
      <xs:element name="VmeSmp"             type="VmeSmpType"/>
      <xs:element name="VmeRm"              type="VmeModuleType"/>
      <xs:element name="VmeAmt"             type="VmeModuleType"/>
      <xs:element name="VmeUmem"            type="VmeModuleType"/>
      <xs:element name="HBJTimeStamp"       type="VmeModuleType"/>
      <xs:element name="VVmeCamacRm"        type="VmeModuleType"/>
      <xs:element name="VVmeFERA4300B"      type="VmeModuleType"/>
      <xs:element name="VVmeCoinReg"        type="VmeModuleType"/>
      <xs:element name="APVDaq"             type="VmeModuleType"/>
      <xs:element name="VmeV1290A"          type="VmeModuleType"/>

      <xs:element name="Tko"                type="TkoType"/>
      <xs:element name="TkoDrT"             type="TkoType"/>
      <xs:element name="TkoDrTII"           type="TkoType"/>
      <xs:element name="TkoMHTdc"           type="TkoMHTdcType"/>
      <xs:element name="TkoMHTdcCSds"       type="TkoMHTdcCSdsType"/>
      <xs:element name="TkoRm"              type="TkoRmType"/>

      <xs:element name="FeraAD413A"         type="FeraType"/>
      <xs:element name="Fera3377"           type="FeraType"/>

      <xs:element name="FinessePtdc"        type="FinesseType"/>
      <xs:element name="FinesseEncoder"     type="FinesseType"/>
      <xs:element name="FinesseEncoderPPG"  type="FinesseType"/>
      <xs:element name="FinesseEncoderPtdc" type="FinesseType"/>

      <xs:element name="FE"  type="FEType"/>
      <xs:element name="for" type="fe_forType"/>
    </xs:choice>
  </xs:group>


  <!-- ______________________________________________________________________-->
  <!-- ______________________________________________________________________-->
  <!-- _________________________________________________________________________
       complexType definition
  -->
  <!-- _________________________________________________________________________
       <channel_mapType>
  -->
  <xs:complexType name="channel_mapType">
    <xs:group ref="nodeGroup"/>
  </xs:complexType>

  <!-- _________________________________________________________________________
       <DType>
  -->
  <xs:complexType name="DType">
    <xs:attribute name="Device"	 type="xs:string" use="optional"/>
    <xs:attribute name="device"	 type="xs:string" default="0"/>
    <xs:attribute name="Plane"   type="xs:string" use="optional"/>
    <xs:attribute name="plane"   type="xs:string" default="0"/>
    <xs:attribute name="Segment" type="xs:string" use="optional"/>
    <xs:attribute name="segment" type="xs:string" default="0"/>
    <xs:attribute name="Ch"      type="xs:string" use="optional"/>
    <xs:attribute name="ch"      type="xs:string" default="0"/>
    <xs:attribute name="Data"    type="xs:string" use="optional"/>
    <xs:attribute name="data"    type="xs:string" default="0"/>
  </xs:complexType>

  <!-- _________________________________________________________________________
       <FEType>
  -->
  <xs:complexType name="FEType">
    <xs:all>
      <xs:element name="D" type="DType"/>
    </xs:all>
    <xs:attribute name="ch"   type="xs:string" default="0"/>
    <xs:attribute name="data" type="xs:string" default="0"/>
  </xs:complexType>

  <!-- _________________________________________________________________________
       <FinesseType>
  -->
  <xs:complexType name="FinesseType">
    <xs:group     ref="feGroup" minOccurs="0" maxOccurs="unbounded"/>
    <xs:attributeGroup ref="finesseAttrs"/>
  </xs:complexType>

  <!-- _________________________________________________________________________
       <TkoType>
  -->
  <xs:complexType name="TkoType">
    <xs:group ref="feGroup" minOccurs="0" maxOccurs="32"/>
    <xs:attributeGroup ref="tkoAttrs"/>
  </xs:complexType>

  <!-- _________________________________________________________________________
       <TkoRmType>
  -->
  <xs:complexType name="TkoRmType">
    <xs:group ref="feGroup" minOccurs="0" maxOccurs="4"/>
    <xs:attributeGroup ref="tkoAttrs"/>
  </xs:complexType>
  <!-- _________________________________________________________________________
       <TkoMHTdcType>
  -->
  <xs:complexType name="TkoMHTdcType">
    <xs:group ref="feGroup" minOccurs="0" maxOccurs="130"/>
    <xs:attributeGroup ref="tkoAttrs"/>
  </xs:complexType>

  <!-- _________________________________________________________________________
       <TkoMHTdcCSdsType>
  -->
  <xs:complexType name="TkoMHTdcCSdsType">
    <xs:group ref="feGroup" minOccurs="0" maxOccurs="130"/>
    <xs:attributeGroup ref="tkoAttrs"/>
  </xs:complexType>

  <!-- _________________________________________________________________________
       <FeraType>
  -->
  <xs:complexType name="FeraType">
    <xs:group ref="feGroup" minOccurs="0" maxOccurs="32"/>
    <xs:attributeGroup ref="feraAttrs"/>
  </xs:complexType>


  <!-- _________________________________________________________________________
       <VmeSmpType>
  -->
  <xs:complexType name="VmeSmpType">
    <xs:group ref="tkoGroup" minOccurs="0" maxOccurs="unbounded"/>
    <xs:attributeGroup ref="vmeAttrs"/>
  </xs:complexType>

  <!-- _________________________________________________________________________
       <VmeUmemType>
  -->
  <xs:complexType name="VmeUmemType">
    <xs:group ref="feraGroup" minOccurs="0" maxOccurs="unbounded"/>
    <xs:attributeGroup ref="vmeAttrs"/>
  </xs:complexType>

  <!-- _________________________________________________________________________
       <VmeModuleType>
  -->
  <xs:complexType name="VmeModuleType">
    <xs:group ref="feGroup" minOccurs="0" maxOccurs="unbounded"/>
    <xs:attributeGroup ref="vmeAttrs"/>
  </xs:complexType>

  <!-- _________________________________________________________________________
       <VmeMasterType>
  -->
  <xs:complexType name="VmeMasterType">
    <xs:group ref="vmeModuleGroup" minOccurs="0" maxOccurs="unbounded"/>
    <xs:attributeGroup ref="nodeAttrs"/>
  </xs:complexType>
  <!-- _________________________________________________________________________
       <CopperType>
  -->
  <xs:complexType name="CopperType">
    <xs:group ref="finesseGroup" minOccurs="0" maxOccurs="4"/>
    <xs:attributeGroup ref="nodeAttrs"/>
  </xs:complexType>

  <!-- _________________________________________________________________________
       <DAQNodeType>
  -->
  <xs:complexType name="DAQNodeType">
    <xs:group ref="nodeGroup" minOccurs="0" maxOccurs="unbounded"/>
    <xs:attributeGroup ref="nodeAttrs"/>
  </xs:complexType>

  <!-- _________________________________________________________________________
       <fe_forType>
  -->
  <xs:complexType name="fe_forType">
    <xs:group     ref="unpackerLoopGroup" minOccurs="0" maxOccurs="unbounded"/>
    <xs:attribute name="var"  type="xs:string" use="required"/>
    <xs:attribute name="from" type="xs:string" use="required"/>
    <xs:attribute name="to"   type="xs:string" use="required"/>
    <xs:attribute name="step" type="xs:int"    default="1"/>
  </xs:complexType>

</xs:schema>

=== jparc-k18/k18-analyzer/param/CMAP/channel_map_20201209.xml
<?xml version="1.0" encoding="UTF-8" ?>

<channel_map xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:noNamespaceSchemaLocation="schema/channel_map.xsd">

  <!--________________________________________________________________-->
  <DAQNode node_id="1" name="k18eb">
    <!--________________________________________________________________-->
    <VmeMaster node_id="0x201" name="vme01">
      <VmeRm address="0xff010000">
    	<for var="ch" from="0" to="1"><for var="data" from="0" to="3">
    	  <FE ch="ch" data="data">
    	  <D Device="VME-RM" Plane="vme01" ch="ch" data="data"/></FE>
    	</for></for>
      </VmeRm>
      <VmeCaenV792 address="0xad010000">
    	<for var="ch" from="0" to="25">
    	  <FE ch="ch"><D Device="VMEdummy" plane="0" segment="ch" data="0"/></FE>
    	</for>
	<FE ch="26"><D Device="BAC" segment="0" ch="0" data="0"/></FE>
	<FE ch="27"><D Device="BAC" segment="1" ch="0" data="0"/></FE>
        <FE ch="28"><D Device="PVAC" segment="0" ch="0" data="0"/></FE>
        <FE ch="29"><D Device="FAC" segment="0" ch="0" data="0"/></FE>
    	<for var="ch" from="30" to="31">
    	  <FE ch="ch"><D Device="VMEdummy" plane="0" segment="ch" data="0"/></FE>
    	</for>
      </VmeCaenV792>
      <VmeCaenV792 address="0xad020000">
	<for var="ch" from="0" to="4">
	  <FE ch="ch*2"><D Device="BH2" segment="ch" ch="0" data="0"/></FE>
	</for>
	<for var="ch" from="5" to="15"><!-- VMEdummy -->
    	  <FE ch="ch*2"><D Device="VMEdummy" plane="1" segment="ch" data="0"/></FE>
    	</for>
      </VmeCaenV792>
      <VmeCaenV792 address="0xad030000">
        <for var="ch" from="0" to="16">
          <FE ch="ch"><D Device="TOF" segment="ch" ch="0" data="0"/></FE>
        </for>
        <FE ch="17"><D Device="VMEdummy" plane="2" segment="17" data="0"/></FE>
        <FE ch="18"><D Device="TOF" segment="18" ch="0" data="0"/></FE>
        <FE ch="19"><D Device="VMEdummy" plane="2" segment="19" data="0"/></FE>
        <FE ch="20"><D Device="TOF" segment="20" ch="0" data="0"/></FE>
        <FE ch="21"><D Device="VMEdummy" plane="2" segment="21" data="0"/></FE>
        <FE ch="22"><D Device="TOF" segment="22" ch="0" data="0"/></FE>
        <FE ch="23"><D Device="VMEdummy" plane="2" segment="23" data="0"/></FE>
        <FE ch="24"><D Device="TOF" segment="17" ch="0" data="0"/></FE>
        <FE ch="25"><D Device="VMEdummy" plane="2" segment="25" data="0"/></FE>
        <FE ch="26"><D Device="TOF" segment="19" ch="0" data="0"/></FE>
        <FE ch="27"><D Device="TOF" segment="21" ch="0" data="0"/></FE>
        <FE ch="28"><D Device="TOF" segment="23" ch="0" data="0"/></FE>
        <for var="ch" from="29" to="31">
          <FE ch="ch"><D Device="VMEdummy" plane="2" segment="ch" data="0"/></FE>
        </for>
      </VmeCaenV792>
      <VmeCaenV792 address="0xad040000">
        <for var="ch" from="0" to="4">
          <FE ch="ch"><D Device="TOF" segment="ch" ch="1" data="0"/></FE>
        </for>
        <FE ch="5"><D Device="VMEdummy" plane="3" segment="5" data="0"/></FE>
        <for var="ch" from="6" to="12">
          <FE ch="ch"><D Device="TOF" segment="ch" ch="1" data="0"/></FE>
        </for>
        <FE ch="13"><D Device="VMEdummy" plane="3" segment="13" data="0"/></FE>
        <for var="ch" from="14" to="16">
          <FE ch="ch"><D Device="TOF" segment="ch" ch="1" data="0"/></FE>
        </for>
        <FE ch="17"><D Device="VMEdummy" plane="3" segment="17" data="0"/></FE>
        <for var="ch" from="18" to="23">
          <FE ch="ch"><D Device="TOF" segment="ch" ch="1" data="0"/></FE>
        </for>
        <FE ch="24"><D Device="VMEdummy" plane="3" segment="24" data="0"/></FE>
        <FE ch="25"><D Device="VMEdummy" plane="3" segment="25" data="0"/></FE>
        <FE ch="26"><D Device="TOF" segment="5" ch="1" data="0"/></FE>
        <FE ch="27"><D Device="VMEdummy" plane="3" segment="27" data="0"/></FE>
        <FE ch="28"><D Device="TOF" segment="13" ch="1" data="0"/></FE>
        <FE ch="29"><D Device="TOF" segment="17" ch="1" data="0"/></FE>
        <FE ch="30"><D Device="VMEdummy" plane="3" segment="30" data="0"/></FE>
        <FE ch="31"><D Device="VMEdummy" plane="3" segment="31" data="0"/></FE>
      </VmeCaenV792>
      <VmeCaenV792 address="0xad050000">
    	<FE ch="0"><D Device="BH1" segment="0" ch="0" data="0"/></FE>
    	<FE ch="1"><D Device="BH1" segment="1" ch="0" data="0"/></FE>
    	<FE ch="2"><D Device="BH1" segment="2" ch="0" data="0"/></FE>
    	<FE ch="3"><D Device="BH1" segment="3" ch="0" data="0"/></FE>
    	<FE ch="4"><D Device="BH1" segment="4" ch="0" data="0"/></FE>
    	<FE ch="5"><D Device="BH1" segment="5" ch="0" data="0"/></FE>
    	<FE ch="6"><D Device="BH1" segment="6" ch="0" data="0"/></FE>
    	<FE ch="7"><D Device="BH1" segment="7" ch="0" data="0"/></FE>
    	<FE ch="8"><D Device="BH1" segment="8" ch="0" data="0"/></FE>
    	<FE ch="9"><D Device="BH1" segment="9" ch="0" data="0"/></FE>
    	<FE ch="10"><D Device="BH1" segment="10" ch="0" data="0"/></FE>
    	<for var="ch" from="11" to="15">
    	  <FE ch="ch"><D Device="VMEdummy" plane="0" segment="ch" data="0"/></FE>
    	</for>
    	<FE ch="16"><D Device="BH1" segment="0" ch="1" data="0"/></FE>
    	<FE ch="17"><D Device="BH1" segment="1" ch="1" data="0"/></FE>
    	<FE ch="18"><D Device="BH1" segment="2" ch="1" data="0"/></FE>
    	<FE ch="19"><D Device="BH1" segment="3" ch="1" data="0"/></FE>
    	<FE ch="20"><D Device="BH1" segment="4" ch="1" data="0"/></FE>
    	<FE ch="21"><D Device="BH1" segment="5" ch="1" data="0"/></FE>
    	<FE ch="22"><D Device="BH1" segment="6" ch="1" data="0"/></FE>
    	<FE ch="23"><D Device="BH1" segment="7" ch="1" data="0"/></FE>
    	<FE ch="24"><D Device="BH1" segment="8" ch="1" data="0"/></FE>
    	<FE ch="25"><D Device="BH1" segment="9" ch="1" data="0"/></FE>
    	<FE ch="26"><D Device="BH1" segment="10" ch="1" data="0"/></FE>
    	<for var="ch" from="27" to="31">
    	  <FE ch="ch"><D Device="VMEdummy" plane="0" segment="ch" data="0"/></FE>
    	</for>
      </VmeCaenV792>
    </VmeMaster>
    <!--________________________________________________________________-->
    <VmeMaster node_id="0x202" name="vme02">
      <VmeRm address="0xff020000">
      	<for var="ch" from="0" to="1"><for var="data" from="0" to="3">
      	  <FE ch="ch" data="data">
      	  <D Device="VME-RM" Plane="vme02" ch="ch" data="data"/></FE>
      	</for></for>
      </VmeRm>
      <VmeCaenV792 address="0x00110000">
	<!-- WC-U-1~20 -->
	<for var="ch" from="0" to="19">
	  <FE ch="ch"><D Device="WC" segment="ch" ch="0" data="0"/></FE>
	</for>
	<!-- WC-D-1~12 -->
	<for var="ch" from="0" to="11">
	  <FE ch="ch+20"><D Device="WC" segment="ch" ch="1" data="0"/></FE>
	</for>
      </VmeCaenV792>
      <VmeCaenV792 address="0x00120000">
	<!-- WC-D-13~20 -->
	<for var="ch" from="0" to="6">
	  <FE ch="ch"><D Device="WC" segment="ch+12" ch="1" data="0"/></FE>
	</for>
	<FE ch="31"><D Device="WC" segment="19" ch="1" data="0"/></FE>
	<!-- WC-SUM-1~20 -->
	<for var="ch" from="0" to="15">
	  <FE ch="ch+8"><D Device="WC" segment="ch" ch="2" data="0"/></FE>
	</for>
	<FE ch="24"><D Device="VMEdummy" plane="2" segment="24" data="0"/></FE>
	<for var="ch" from="17" to="19">
	  <FE ch="ch+8"><D Device="WC" segment="ch" ch="2" data="0"/></FE>
	</for>
	<FE ch="28"><D Device="VMEdummy" plane="2" segment="28" data="0"/></FE>
	<FE ch="29"><D Device="WC" segment="16" ch="2" data="0"/></FE>
	<!-- VMEdummy -->
	<FE ch="7"><D Device="VMEdummy" plane="2" segment="7" data="0"/></FE>
	<FE ch="30"><D Device="VMEdummy" plane="2" segment="30" data="0"/></FE>
      </VmeCaenV792>
    </VmeMaster>
    <!--________________________________________________________________-->
    <HulMHTdc node_id="0x611" name="hul02sdc-1">
      <for var="ch" from="0" to="63"><for var="data" from="0" to="2">
    	  <FE ch="ch" data="data"><D Device="SDC3" plane="0" ch="ch" data="data"/></FE>
      </for></for>
      <for var="data" from="0" to="3">
  	<FE ch="0" data="data + 3"><D Device="HUL-RM" plane="hul02sdc_1" ch="0" data="data"/></FE>
      </for>
    </HulMHTdc>
    <HulMHTdc node_id="0x612" name="hul02sdc-2">
      <for var="ch" from="0" to="63"><for var="data" from="0" to="2">
    	  <FE ch="ch" data="data"><D Device="SDC3" plane="0" ch="ch + 64" data="data"/></FE>
      </for></for>
      <for var="ch" from="64" to="127"><for var="data" from="0" to="1">
    	  <FE ch="ch" data="data"><D Device="SDC3" plane="1" ch="ch - 64" data="data"/></FE>
      </for></for>
    </HulMHTdc>
    <HulMHTdc node_id="0x613" name="hul02sdc-3">
      <for var="ch" from="0" to="63"><for var="data" from="0" to="2">
    	  <FE ch="ch" data="data"><D Device="SDC3" plane="1" ch="ch + 64" data="data"/></FE>
      </for></for>
      <for var="ch" from="64" to="127"><for var="data" from="0" to="1">
    	  <FE ch="ch" data="data"><D Device="SDC3" plane="2" ch="191 - ch" data="data"/></FE>
      </for></for>
    </HulMHTdc>
    <HulMHTdc node_id="0x614" name="hul02sdc-4">
      <for var="ch" from="0" to="63"><for var="data" from="0" to="2">
    	  <FE ch="ch" data="data"><D Device="SDC3" plane="2" ch="63 - ch" data="data"/></FE>
      </for></for>
      <for var="ch" from="64" to="127"><for var="data" from="0" to="1">
    	  <FE ch="ch" data="data"><D Device="SDC3" plane="3" ch="191 - ch" data="data"/></FE>
      </for></for>
    </HulMHTdc>
    <HulMHTdc node_id="0x615" name="hul02sdc-5">
      <for var="ch" from="0" to="63"><for var="data" from="0" to="2">
    	  <FE ch="ch" data="data"><D Device="SDC3" plane="3" ch="63 - ch" data="data"/></FE>
      </for></for>
      <for var="ch" from="0" to="31"><for var="data" from="0" to="1">
      	  <FE ch="ch * 2 + 64" data="data"><D Device="SDC4" Plane="x2" ch="ch" data="data"/></FE>
      	  <FE ch="ch * 2 + 65" data="data"><D Device="SDC4" Plane="x1" ch="ch" data="data"/></FE>
      </for></for>
    </HulMHTdc>
    <!--________________________________________________________________-->
    <HulMHTdc node_id="0x616" name="hul02sdc-6">
